version: '3'

services:
  app:
    build: .
    ports:
      - "1001:1001"
    working_dir: "/src"
    volumes:
      - "./src:/src"
      - node_modules_volume:/src/node_modules
    tty: true
volumes:
  node_modules_volume: